services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "8080:8080"      # HTTP transcriber
      - "443:443"    # HTTPS (когда будет домен)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro  # Конфиг (read-only)
      - ./static:/srv:ro					# страница с маршрутами
      - caddy_data:/data                       # SSL сертификаты
      - caddy_config:/config                   # Кэш Caddy
    networks:
      - proxy-net

networks:
  proxy-net:
    name: proxy-net  # Общая сеть для всех демо
    external: true   
volumes:
  caddy_data:
  caddy_config:
